name: "build pipeline for web release"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and push
        run: docker build -t fe-image:latest .

      - name: Stop container
        run: docker stop fe-container
      - name: Remove Container
        run: docker rm fe-container
        
      - name: Run Docker container
        run: docker run -d --name fe-container -p 80:80 fe-image:latest
