name: "build pipeline for web release"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and push
        run: docker build -t fe-image:latest .

      - name: Run Docker container
        run: docker run -d --name fe-container -p 5000:5000 fe-image:latest
